version: 0.2



phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y unzip
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo Jitendra222@ | docker login -u jitendra222 --password-stdin docker.io
  build:
    commands:
      - echo "Building the Docker image..."
      #- echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin docker.io
      - docker build -t Jitendra222@/laravel-app:latest .
      - echo "Pushing the Docker image..."
      - docker push jitendra222/laravel-app:latest
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - appspec.yml
    - scripts/*

cache:
  paths:
    - /root/.composer/cache
